---
- name: Build Mainsail on ***THIS*** host
  delegate_to: localhost
  block:
    - name: Clone mainsail repository
      git:
        repo: "{{ mainsail_repo }}"
        dest: "{{ mainsail_local_build_dir }}"
        version: "{{ mainsail_version }}"
        force: yes

    - name: Apply patch hostname
      patch:
        src: "{{ item }}"
        basedir: "{{ mainsail_local_build_dir }}"
        strip: 1
      loop:
        - disable_service_worker.patch
        - multiple_hostnames.patch

    - name: Install npm dependencies
      npm:
        path: "{{ mainsail_local_build_dir }}"

    - name: Prepare mainsail dependencies
      command: npm ci
      args:
        chdir: "{{ mainsail_local_build_dir }}"

    - name: Build mainsail
      command: npm run build
      args:
        chdir: "{{ mainsail_local_build_dir }}"

- name: Create mainsail www folder
  become: true
  file:
    path: "{{ mainsail_www_dir }}"
    state: directory
    owner: "{{ system_user }}"
    group: www-data

- name: Copy mainsail files to www dir
  unarchive:
    src: "{{ mainsail_local_build_dir }}/dist/mainsail.zip"
    dest: "{{ mainsail_www_dir }}"
  notify: restart nginx

- name: Copy Mainsail config.json
  template:
    src: config.json.j2
    dest: "{{ mainsail_www_dir }}/config.json"
  notify: restart nginx

- name: Copy nginx common vars for mainsail
  become: true
  template:
    src: nginx_common_vars.conf.j2
    dest: /etc/nginx/conf.d/common_vars.conf

- name: Copy nginx upstreams for mainsail
  become: true
  template:
    src: nginx_upstreams.conf.j2
    dest: /etc/nginx/conf.d/upstreams.conf

- name: Copy nginx config for mainsail
  become: true
  template:
    src: nginx_mainsail.conf.j2
    dest: /etc/nginx/sites-available/mainsail

- name: Remove nginx default site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Link mainsail nginx config to enable sites
  become: true
  file:
    src: /etc/nginx/sites-available/mainsail
    dest: /etc/nginx/sites-enabled/mainsail
    state: link
  notify: restart nginx
