---
- name: Setup farmlab
  hosts: farmlab
  roles:
    - role: common
      tags: ['common']

    - role: klipper
      tags: ['klipper']

    - role: moonraker
      tags: ['moonraker']

    - role: mainsail
      tags: ['mainsail']
    - role: oauth2_proxy
      tags: ['oauth2_proxy']
