- name: Copy macros.cfg for {{ printer.name }}
  template:
    src: macros.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ printer.name }}/config/macros.cfg"
  register: cfg_macros

- name: Copy mainsail.cfg for {{ printer.name }}
  template:
    src: mainsail.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ printer.name }}/config/mainsail.cfg"
  register: cfg_mainsail

- name: Copy model.cfg for {{ printer.name }}
  template:
    src: "{{ printer.model }}.cfg.j2"
    dest: "{{ install_dir }}/printer_data_{{ printer.name }}/config/{{ printer.model }}.cfg"
  register: cfg_model

- name: Copy name.cfg for {{ printer.name }}
  template:
    src: "{{ printer.name }}.cfg.j2"
    dest: "{{ install_dir }}/printer_data_{{ printer.name }}/config/{{ printer.name }}.cfg"
  register: cfg_name

- name: Create printer.cfg for {{ printer.name }}
  copy:
    backup: yes
    dest: "{{ install_dir }}/printer_data_{{ printer.name }}/config/printer.cfg"
    content: |
      [include mainsail.cfg]
      [include macros.cfg]

      [include {{ printer.model }}.cfg]
      [include {{ printer.name }}.cfg]

      [mcu]
      serial: /dev/{{ printer.name }}

      ##########################################
      # WARNING
      # Here lies klipper's SAVE_CONFIG
      # You *MUST* move the config overwrites in {{ printer.model }}.cfg in git
      ##########################################
  register: cfg_printer

- name: Restart klipper for {{ printer.name }}
  become: true
  systemd:
    name: "klipper@{{ printer.name }}"
    state: restarted
  when: >
    cfg_macros.changed or
    cfg_mainsail.changed or
    cfg_model.changed or
    cfg_name.changed or
    cfg_printer.changed
