---
- name: Create directory for printer
  file:
    path: "{{ install_dir }}/printer_data_{{ item.0.name }}/{{ item.1 }}"
    state: directory
    mode: 0755
  loop: "{{ printers | product(['config', 'logs', 'comms', 'gcodes']) | list }}"

- name: Copy macros.cfg for printer
  template:
    src: macros.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/macros.cfg"
  loop: "{{ printers }}"
  notify: restart klipper

- name: Copy mainsail.cfg for printer
  template:
    src: mainsail.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/mainsail.cfg"
  loop: "{{ printers }}"
  notify: restart klipper

- name: Copy model.cfg for printer
  template:
    src: "{{ item.model }}.cfg.j2"
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/{{ item.model }}.cfg"
  loop: "{{ printers }}"
  notify: restart klipper
  tags: ['klipper_cfg_printer']

- name: Copy name.cfg for printer
  template:
    src: "{{ item.name }}.cfg.j2"
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/{{ item.name }}.cfg"
  loop: "{{ printers }}"
  notify: restart klipper
  tags: ['klipper_cfg_printer']

- name: Create printer.cfg
  copy:
    backup: yes
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/printer.cfg"
    content: |
      [include mainsail.cfg]
      [include macros.cfg]

      [include {{ item.model }}.cfg]
      [include {{ item.name }}.cfg]

      [mcu]
      serial: /dev/{{ item.name }}

      ##########################################
      # WARNING
      # Here lies klipper's SAVE_CONFIG
      # You *MUST* move the config overwrites in {{ item.model }}.cfg in git
      ##########################################
  loop_control:
    index_var: i
  loop: "{{ printers }}"
  notify: restart klipper
