---
- name: Fetch klipper git repository
  git:
    repo: "{{ klipper_repo }}"
    dest: "{{ install_dir }}/klipper"
    version: "{{ klipper_version }}"

- name: Create klipper python venv
  pip:
    requirements: "{{ install_dir }}/klipper/scripts/klippy-requirements.txt"
    virtualenv: "{{ install_dir }}/klippy-env"
    virtualenv_command: python3 -m venv

- name: Create directory for printer
  file:
    path: "{{ install_dir }}/printer_data_{{ item.0.name }}/{{ item.1 }}"
    state: directory
    mode: 0755
  loop: "{{ printers | product(['config', 'logs', 'comms', 'gcodes']) | list }}"

- name: Copy macros.cfg for printer
  template:
    src: macros.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/macros.cfg"
  loop: "{{ printers }}"
  notify: restart klipper

- name: Copy mainsail.cfg for printer
  template:
    src: mainsail.cfg.j2
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/mainsail.cfg"
  loop: "{{ printers }}"
  notify: restart klipper

- name: Copy printer.cfg for printer
  template:
    src: "{{ item.model }}.cfg.j2"
    dest: "{{ install_dir }}/printer_data_{{ item.name }}/config/printer.cfg"
  loop: "{{ printers }}"
  notify: restart klipper

- name: Create udev rules for printer
  become: true
  template:
    src: udev-printer.rules.j2
    dest: "/etc/udev/rules.d/99-printer-{{ item.name }}.rules"
  loop: "{{ printers }}"
  notify: reload udev

- name: Copy systemd klipper service template
  become: true
  template:
    src: klipper@.service.j2
    dest: /etc/systemd/system/klipper@.service
    mode: 0644
  notify: reload systemd

- name: Enable and start klipper service for printer
  become: true
  systemd:
    name: "klipper@{{ item.name }}"
    enabled: yes
    state: started
  loop: "{{ printers }}"
